### ISSUE TITLE
Failed to load the atom-bitcoin package

### ISSUE THREAD

**Issue by JoeNoPhoto** [ahmetabdi/atom-bitcoin#6]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.202.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-bitcoin](https://github.com/ahmetabdi/atom-bitcoin) package, v0.6.0
### Stack Trace

Failed to load the atom-bitcoin package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users//.atom/packages/atom-bitcoin/lib/atom-bitcoin-status-bar-view.coffee:1:1)
  at /Users//.atom/packages/atom-bitcoin/lib/atom-bitcoin-status-bar-view.coffee:7:3
  at Object.<anonymous> (/Users//.atom/packages/atom-bitcoin/lib/atom-bitcoin-status-bar-view.coffee:89:5)
  at Object.<anonymous> (/Users//.atom/packages/atom-bitcoin/lib/atom-bitcoin-status-bar-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users//.atom/packages/atom-bitcoin/lib/atom-bitcoin.coffee:1:28)
  at Object.<anonymous> (/Users//.atom/packages/atom-bitcoin/lib/atom-bitcoin.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:186:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:177:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:355:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:30)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:345:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:41:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
  3x -0:45.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "jquery-snippets"
    ],
    "projectHome": "/Users//Projects"
  },
  "atom-bitcoin": {}
}
```
### Installed Packages

``` coffee
# User
atom-bitcoin, v0.6.0
atom-html-preview, v0.1.6
block-cursor, v0.12.5
color-picker, v2.0.2
emmet, v2.3.10
file-icons, v1.5.5
javascript-snippets, v1.0.0
linter, v0.12.6
linter-coffeelint, v0.2.4
linter-csslint, v0.0.13
linter-eslint, v0.5.8
linter-htmlhint, v0.0.16
linter-jsonlint, v0.1.4
linter-scss-lint, v1.0.4
linter-tidy, v1.0.1
local-history, v3.1.0
project-manager, v1.15.7
script, v2.23.0
wordcount, v2.2.2

# Dev
No dev packages
```

**Comment by grillons** [comment]
+1 

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [atom-bitcoin](https://github.com/ahmetabdi/atom-bitcoin) package 0.6.0


### Stack Trace

Failed to load the atom-bitcoin package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at extend (/packages/atom-bitcoin/lib/atom-bitcoin-status-bar-view.coffee:1:1)
    at /packages/atom-bitcoin/lib/atom-bitcoin-status-bar-view.coffee:6:7
    at /packages/atom-bitcoin/lib/atom-bitcoin-status-bar-view.coffee:66:12)
    at /packages/atom-bitcoin/lib/atom-bitcoin-status-bar-view.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-bitcoin/lib/atom-bitcoin.coffee:1:28)
    at /packages/atom-bitcoin/lib/atom-bitcoin.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:794:28
```

### Commands

```
     -0:14.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
activate-power-mode 1.2.0 
atom-bitcoin 0.6.0 
emmet 2.4.3 
file-icons 2.0.15 
language-slim 0.5.0 
linter 1.11.23 
linter-csslint 1.3.3 
linter-rubocop 0.5.3 
linter-sass-lint 1.7.4 
linter-scss-lint 3.0.4 
minimap 4.26.8 
pigments 0.39.0 
rest-client 1.3.1 
```

**Comment by qjawe** [comment]
same problem

**Comment by cyril** [comment]
I recommend this (minimalist) alternative: [BTC Status Bar](https://atom.io/packages/btc-status-bar)

**Comment by octocat69** [comment]
- [x**** ] - ,[x]

**Comment by octocat69** [comment]
2021 © Hyperwallet Systems Inc.

Developer Terms of Use - Privacy Policy - Corporate - Contact Us - Documentation

**Comment by octocat69** [comment]
Please require atom-space-pen-views instead:
{View} = require 'atom-space-pen-views'
Add "atom-space-pen-views": "^2.0.3" to your package dependencies.

Object.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/exports/atom.js:61:9)

**Comment by octocat69** [comment]
```

```

**Comment by octocat69** [comment]
Installed Packages

# User
atom-bitcoin, v0.6.0
atom-html-preview, v0.1.6
block-cursor, v0.12.5
color-picker, v2.0.2
emmet, v2.3.10
file-icons, v1.5.5
javascript-snippets, v1.0.0
linter, v0.12.6
linter-coffeelint, v0.2.4
linter-csslint, v0.0.13
